{{- if and .Values.persistence.logs.enabled (not .Values.persistence.logs.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "app.fullname" . }}-logs
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.persistence.logs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ if .Values.persistence.logs.accessMode }}{{ .Values.persistence.logs.accessMode | quote }}{{- else }}{{ .Values.persistence.accessMode | quote }}{{- end }}
  resources:
    requests:
      storage: {{ if .Values.persistence.logs.size }}{{ .Values.persistence.logs.size | quote }}{{- else }}{{ .Values.persistence.size | quote }}{{- end }}
  {{- if or .Values.persistence.storageClass .Values.persistence.logs.storageClass }}
  storageClassName: {{ (coalesce .Values.persistence.logs.storageClass .Values.persistence.storageClass) | quote }}
  {{- end }}
{{- end }}
