apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--serversTransport.insecureSkipVerify=true"
    service:
      spec:
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false
    ports:
      traefik:
        expose: true
      websecure:
        forwardedHeaders:
          insecure: true
        proxyProtocol:
          insecure: true
        tls:
          enabled: true
      web:
        forwardedHeaders:
          insecure: true
        proxyProtocol:
          insecure: true
        redirectTo:
          port: websecure
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
