{{- if .Values.environment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configmap.environment" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  APP: {{ .Values.environment.app | quote }}
{{- end }}
